# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('message_date', models.DateTimeField(verbose_name='sending_date')),
                ('message_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServerApp.Author')),
            ],
        ),
    ]
